[tool.poetry]
name = "stegano"
version = "0.1.0"
description = ""
authors = ["Seb Mascha <sebastien.mascha@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^8.2.0"
piexif = "^1.1.3"
crayons = "^0.4.0"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
flake8 = "^3.9.0"
nose2 = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
